
GET  https://localhost/Darasgah_mag/Android_api/test.php






###
POST https://localhost/Darasgah_mag/Android_api/login.php HTTP/1.1
content-type: application/x-www-form-urlencoded
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJsb2NhbGhvc3QiLCJhdWQiOiJ5YmhhdDM5QGdtYWlsLmNvbSIsImlhdCI6MTY3MTYwMzczNSwiZXhwIjoxNjcxNjA3MzM1LCJuYmYiOjM2MDAwfQ.-O2zLOuGblFd3MUIGo6t0pS1u3pjFIIr-wTLriwYr2Y

refresh=1

### LOGIN###############################################
POST https://localhost/Darasgah_mag/Android_api/login.php HTTP/1.1
content-type: application/x-www-form-urlencoded
# Authorization: Bearer 

email=ybhat39@gmail.com&password=12345
###
POST https://localhost/Darasgah_mag/Android_api/getSetData.php
content-type: application/x-www-form-urlencoded
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJsb2NhbGhvc3QiLCJhdWQiOiJ5YmhhdDM5QGdtYWlsLmNvbSIsImlhdCI6MTY3MzQ1NzEwMywiZXhwIjoxNjczNDU3NzAzLCJuYmYiOjE2NzM0NTcxMDN9.Xa3-wYIIs0x7Lu0MtQsmSUr3QecN1HdtO5U20ISV5Ak

action=setDebitData&amount=1020&by=me&for=food


###
POST https://localhost/Darasgah_mag/Android_api/getSetData.php
content-type: application/x-www-form-urlencoded
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJsb2NhbGhvc3QiLCJhdWQiOiJ5YmhhdDM5QGdtYWlsLmNvbSIsImlhdCI6MTY3MzQ2MDcyNiwiZXhwIjoxNjczNDYxMzI2LCJuYmYiOjE2NzM0NjA3MjZ9.ezqTnBfUHsVP2N6sifht7vDhj3yPLX5qMD6U3hkBY9c

action=getLineChatData&table=cr&year=2023


###
POST https://localhost/Darasgah_mag/Android_api/logout.php
content-type: application/x-www-form-urlencoded
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJsb2NhbGhvc3QiLCJhdWQiOiJ5YmhhdDM5QGdtYWlsLmNvbSIsImlhdCI6MTY3MTYxNzY4NiwiZXhwIjoxNjcxNjIxMjg2LCJuYmYiOjM2MDAwfQ.3rsGt6MDILtQYrgtxUkilOftlVLKJqandr3ipB7

