
GET  https://localhost/Darasgah_mag/Android_api/test.php






###
POST https://localhost/Darasgah_mag/Android_api/login.php HTTP/1.1
content-type: application/x-www-form-urlencoded
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJsb2NhbGhvc3QiLCJhdWQiOiJ5YmhhdDM5QGdtYWlsLmNvbSIsImlhdCI6MTY3NDQ2NjM1NywiZXhwIjoxNjc0NDY2OTU3LCJuYmYiOjE2NzQ0NjYzNTd9.1u3FIojmJ7lJ2XLy7wiOvsjQxj1GCvcqMrAnUfKjm0Q

refresh=1

### LOGIN###############################################
POST https://localhost/Darasgah_mag/Android_api/login.php HTTP/1.1
content-type: application/x-www-form-urlencoded
# Authorization: Bearer 

email=ybhat39@gmail.com&password=12345
###
POST https://localhost/Darasgah_mag/Android_api/getSetData.php
content-type: application/x-www-form-urlencoded
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJsb2NhbGhvc3QiLCJhdWQiOiJ5YmhhdDM5QGdtYWlsLmNvbSIsImlhdCI6MTY3NDQ2NjM1NywiZXhwIjoxNjc0NDY2OTU3LCJuYmYiOjE2NzQ0NjYzNTd9.1u3FIojmJ7lJ2XLy7wiOvsjQxj1GCvcqMrAnUfKjm0Q

action=setDebitData&amount=1020&by=me&for=food


###
POST https://localhost/Darasgah_mag/Android_api/getSetData.php
content-type: application/x-www-form-urlencoded
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJsb2NhbGhvc3QiLCJhdWQiOiJ5YmhhdDM5QGdtYWlsLmNvbSIsImlhdCI6MTY3MzczMzY3MiwiZXhwIjoxNjczNzM0MjcyLCJuYmYiOjE2NzM3MzM2NzJ9.cm8flFAjDvCRUPYmGzpFNdBAQ9seNgZgEvLXdOSfIos

action=getDebitData&year=2023


###
POST https://localhost/Darasgah_mag/Android_api/logout.php
content-type: application/x-www-form-urlencoded
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJsb2NhbGhvc3QiLCJhdWQiOiJ5YmhhdDM5QGdtYWlsLmNvbSIsImlhdCI6MTY3MTYxNzY4NiwiZXhwIjoxNjcxNjIxMjg2LCJuYmYiOjM2MDAwfQ.3rsGt6MDILtQYrgtxUkilOftlVLKJqandr3ipB7

